#!/usr/bin/env escript
%%! -pa ../deps/epgsql/ebin ../deps/bcrypt/ebin

main([]) ->
    io:put_chars("Usage:\n\tset-password username password\n");
main([UserName, Password]) ->
    {ok, _} = application:ensure_all_started(bcrypt),
    {ok, Salt} = bcrypt:gen_salt(),
    {ok, Hash} = bcrypt:hashpw(Password, Salt),

    {ok, C} = pgsql:connect("localhost", "blerg", "", [{database, "blerg"}]),
    pgsql:equery(C, "UPDATE users SET password_hash = $1 WHERE name = $2", [Hash, UserName]),
    pgsql:close(C).

%% -*- erlang -*-
%% vim: ft=erlang
